version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /interaction/gui/web
    schedule:
      interval: weekly
      day: tuesday
      time: "02:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    groups:
      gui-development-minor-patch:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      gui-production-minor-patch:
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /official
    schedule:
      interval: weekly
      day: wednesday
      time: "02:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    groups:
      website-development-minor-patch:
        dependency-type: development
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      website-production-minor-patch:
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: thursday
      time: "02:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
