// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {view} from '../models';

export function Abort():Promise<void>;

export function ClearSelectedSkill():Promise<void>;

export function ContextReport():Promise<string>;

export function ContextSnapshot():Promise<view.ContextSnapshot>;

export function ContextStatus():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<view.ConfigView>;

export function GetSkillManagement():Promise<view.SkillManagementView>;

export function ListSessions():Promise<Array<view.SessionMeta>>;

export function LoadSession(arg1:string):Promise<Array<view.DisplayMessage>>;

export function NewSession():Promise<view.SessionMeta>;

export function ProviderModel():Promise<string>;

export function ReadImageBase64(arg1:string):Promise<string>;

export function RefreshSkillManagement():Promise<view.SkillManagementView>;

export function ReplyConfirm(arg1:string,arg2:boolean):Promise<void>;

export function ReplyConfirmDecision(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function ReplyConfirmWithPermission(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<void>;

export function ReplyQuestion(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveConfig(arg1:view.ConfigView):Promise<view.ConfigView>;

export function SelectSkill(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<view.SkillManagementView>;

export function SwitchModel(arg1:string):Promise<string>;
